const nutritionDataInitial = [
    {
        kilokalorie: 0,
        bialka: 0,
        weglowodany: 0,
        blonnik: 0,
        cukry: 0,
        sole: 0,
        magnez: 0,
        wapn: 0,
        chlor: 0,
        potas: 0,
        fosfor: 0,
        tluszcze: 0,
        ilosc: 0

    },
    {
        kilokalorie: 0,
        bialka: 0,
        weglowodany: 0,
        blonnik: 0,
        cukry: 0,
        sole: 0,
        magnez: 0,
        wapn: 0,
        chlor: 0,
        potas: 0,
        fosfor: 0,
        tluszcze: 0,
        ilosc: 0
    },
    {
        kilokalorie: 0,
        bialka: 0,
        weglowodany: 0,
        blonnik: 0,
        cukry: 0,
        sole: 0,
        magnez: 0,
        wapn: 0,
        chlor: 0,
        potas: 0,
        fosfor: 0,
        tluszcze: 0,
        ilosc: 0
    },
    {
        kilokalorie: 0,
        bialka: 0,
        weglowodany: 0,
        blonnik: 0,
        cukry: 0,
        sole: 0,
        magnez: 0,
        wapn: 0,
        chlor: 0,
        potas: 0,
        fosfor: 0,
        tluszcze: 0,
        ilosc: 0
    },
    {
        kilokalorie: 0,
        bialka: 0,
        weglowodany: 0,
        blonnik: 0,
        cukry: 0,
        sole: 0,
        magnez: 0,
        wapn: 0,
        chlor: 0,
        potas: 0,
        fosfor: 0,
        tluszcze: 0,
        ilosc: 0
    },
    {
        kilokalorie: 0,
        bialka: 0,
        weglowodany: 0,
        blonnik: 0,
        cukry: 0,
        sole: 0,
        magnez: 0,
        wapn: 0,
        chlor: 0,
        potas: 0,
        fosfor: 0,
        tluszcze: 0,
        ilosc: 0
    },
    {
        kilokalorie: 0,
        bialka: 0,
        weglowodany: 0,
        blonnik: 0,
        cukry: 0,
        sole: 0,
        magnez: 0,
        wapn: 0,
        chlor: 0,
        potas: 0,
        fosfor: 0,
        tluszcze: 0,
        ilosc: 0
    }
];

export default nutritionDataInitial;
